// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/CommonIndexFileFormat.proto

package io.osirrc.ciff;

public final class CommonIndexFileFormat {
  private CommonIndexFileFormat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.osirrc.ciff.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 num_postings_lists = 1;</code>
     */
    int getNumPostingsLists();

    /**
     * <code>int32 num_docs = 2;</code>
     */
    int getNumDocs();
  }
  /**
   * Protobuf type {@code io.osirrc.ciff.Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.osirrc.ciff.Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Header();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              numPostingsLists_ = input.readInt32();
              break;
            }
            case 16: {

              numDocs_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_Header_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.osirrc.ciff.CommonIndexFileFormat.Header.class, io.osirrc.ciff.CommonIndexFileFormat.Header.Builder.class);
    }

    public static final int NUM_POSTINGS_LISTS_FIELD_NUMBER = 1;
    private int numPostingsLists_;
    /**
     * <code>int32 num_postings_lists = 1;</code>
     */
    public int getNumPostingsLists() {
      return numPostingsLists_;
    }

    public static final int NUM_DOCS_FIELD_NUMBER = 2;
    private int numDocs_;
    /**
     * <code>int32 num_docs = 2;</code>
     */
    public int getNumDocs() {
      return numDocs_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numPostingsLists_ != 0) {
        output.writeInt32(1, numPostingsLists_);
      }
      if (numDocs_ != 0) {
        output.writeInt32(2, numDocs_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numPostingsLists_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, numPostingsLists_);
      }
      if (numDocs_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numDocs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.osirrc.ciff.CommonIndexFileFormat.Header)) {
        return super.equals(obj);
      }
      io.osirrc.ciff.CommonIndexFileFormat.Header other = (io.osirrc.ciff.CommonIndexFileFormat.Header) obj;

      if (getNumPostingsLists()
          != other.getNumPostingsLists()) return false;
      if (getNumDocs()
          != other.getNumDocs()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUM_POSTINGS_LISTS_FIELD_NUMBER;
      hash = (53 * hash) + getNumPostingsLists();
      hash = (37 * hash) + NUM_DOCS_FIELD_NUMBER;
      hash = (53 * hash) + getNumDocs();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.osirrc.ciff.CommonIndexFileFormat.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.osirrc.ciff.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.osirrc.ciff.Header)
        io.osirrc.ciff.CommonIndexFileFormat.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_Header_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.osirrc.ciff.CommonIndexFileFormat.Header.class, io.osirrc.ciff.CommonIndexFileFormat.Header.Builder.class);
      }

      // Construct using io.osirrc.ciff.CommonIndexFileFormat.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numPostingsLists_ = 0;

        numDocs_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_Header_descriptor;
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.Header getDefaultInstanceForType() {
        return io.osirrc.ciff.CommonIndexFileFormat.Header.getDefaultInstance();
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.Header build() {
        io.osirrc.ciff.CommonIndexFileFormat.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.Header buildPartial() {
        io.osirrc.ciff.CommonIndexFileFormat.Header result = new io.osirrc.ciff.CommonIndexFileFormat.Header(this);
        result.numPostingsLists_ = numPostingsLists_;
        result.numDocs_ = numDocs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.osirrc.ciff.CommonIndexFileFormat.Header) {
          return mergeFrom((io.osirrc.ciff.CommonIndexFileFormat.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.osirrc.ciff.CommonIndexFileFormat.Header other) {
        if (other == io.osirrc.ciff.CommonIndexFileFormat.Header.getDefaultInstance()) return this;
        if (other.getNumPostingsLists() != 0) {
          setNumPostingsLists(other.getNumPostingsLists());
        }
        if (other.getNumDocs() != 0) {
          setNumDocs(other.getNumDocs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.osirrc.ciff.CommonIndexFileFormat.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.osirrc.ciff.CommonIndexFileFormat.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int numPostingsLists_ ;
      /**
       * <code>int32 num_postings_lists = 1;</code>
       */
      public int getNumPostingsLists() {
        return numPostingsLists_;
      }
      /**
       * <code>int32 num_postings_lists = 1;</code>
       */
      public Builder setNumPostingsLists(int value) {
        
        numPostingsLists_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num_postings_lists = 1;</code>
       */
      public Builder clearNumPostingsLists() {
        
        numPostingsLists_ = 0;
        onChanged();
        return this;
      }

      private int numDocs_ ;
      /**
       * <code>int32 num_docs = 2;</code>
       */
      public int getNumDocs() {
        return numDocs_;
      }
      /**
       * <code>int32 num_docs = 2;</code>
       */
      public Builder setNumDocs(int value) {
        
        numDocs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 num_docs = 2;</code>
       */
      public Builder clearNumDocs() {
        
        numDocs_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.osirrc.ciff.Header)
    }

    // @@protoc_insertion_point(class_scope:io.osirrc.ciff.Header)
    private static final io.osirrc.ciff.CommonIndexFileFormat.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.osirrc.ciff.CommonIndexFileFormat.Header();
    }

    public static io.osirrc.ciff.CommonIndexFileFormat.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      @java.lang.Override
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.osirrc.ciff.CommonIndexFileFormat.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PostingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.osirrc.ciff.Posting)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 docid = 1;</code>
     */
    int getDocid();

    /**
     * <code>int32 tf = 2;</code>
     */
    int getTf();
  }
  /**
   * Protobuf type {@code io.osirrc.ciff.Posting}
   */
  public  static final class Posting extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.osirrc.ciff.Posting)
      PostingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Posting.newBuilder() to construct.
    private Posting(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Posting() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Posting();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Posting(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              docid_ = input.readInt32();
              break;
            }
            case 16: {

              tf_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_Posting_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_Posting_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.osirrc.ciff.CommonIndexFileFormat.Posting.class, io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder.class);
    }

    public static final int DOCID_FIELD_NUMBER = 1;
    private int docid_;
    /**
     * <code>int32 docid = 1;</code>
     */
    public int getDocid() {
      return docid_;
    }

    public static final int TF_FIELD_NUMBER = 2;
    private int tf_;
    /**
     * <code>int32 tf = 2;</code>
     */
    public int getTf() {
      return tf_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (docid_ != 0) {
        output.writeInt32(1, docid_);
      }
      if (tf_ != 0) {
        output.writeInt32(2, tf_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (docid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, docid_);
      }
      if (tf_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, tf_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.osirrc.ciff.CommonIndexFileFormat.Posting)) {
        return super.equals(obj);
      }
      io.osirrc.ciff.CommonIndexFileFormat.Posting other = (io.osirrc.ciff.CommonIndexFileFormat.Posting) obj;

      if (getDocid()
          != other.getDocid()) return false;
      if (getTf()
          != other.getTf()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOCID_FIELD_NUMBER;
      hash = (53 * hash) + getDocid();
      hash = (37 * hash) + TF_FIELD_NUMBER;
      hash = (53 * hash) + getTf();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.Posting parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.osirrc.ciff.CommonIndexFileFormat.Posting prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.osirrc.ciff.Posting}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.osirrc.ciff.Posting)
        io.osirrc.ciff.CommonIndexFileFormat.PostingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_Posting_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_Posting_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.osirrc.ciff.CommonIndexFileFormat.Posting.class, io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder.class);
      }

      // Construct using io.osirrc.ciff.CommonIndexFileFormat.Posting.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        docid_ = 0;

        tf_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_Posting_descriptor;
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.Posting getDefaultInstanceForType() {
        return io.osirrc.ciff.CommonIndexFileFormat.Posting.getDefaultInstance();
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.Posting build() {
        io.osirrc.ciff.CommonIndexFileFormat.Posting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.Posting buildPartial() {
        io.osirrc.ciff.CommonIndexFileFormat.Posting result = new io.osirrc.ciff.CommonIndexFileFormat.Posting(this);
        result.docid_ = docid_;
        result.tf_ = tf_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.osirrc.ciff.CommonIndexFileFormat.Posting) {
          return mergeFrom((io.osirrc.ciff.CommonIndexFileFormat.Posting)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.osirrc.ciff.CommonIndexFileFormat.Posting other) {
        if (other == io.osirrc.ciff.CommonIndexFileFormat.Posting.getDefaultInstance()) return this;
        if (other.getDocid() != 0) {
          setDocid(other.getDocid());
        }
        if (other.getTf() != 0) {
          setTf(other.getTf());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.osirrc.ciff.CommonIndexFileFormat.Posting parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.osirrc.ciff.CommonIndexFileFormat.Posting) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int docid_ ;
      /**
       * <code>int32 docid = 1;</code>
       */
      public int getDocid() {
        return docid_;
      }
      /**
       * <code>int32 docid = 1;</code>
       */
      public Builder setDocid(int value) {
        
        docid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 docid = 1;</code>
       */
      public Builder clearDocid() {
        
        docid_ = 0;
        onChanged();
        return this;
      }

      private int tf_ ;
      /**
       * <code>int32 tf = 2;</code>
       */
      public int getTf() {
        return tf_;
      }
      /**
       * <code>int32 tf = 2;</code>
       */
      public Builder setTf(int value) {
        
        tf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 tf = 2;</code>
       */
      public Builder clearTf() {
        
        tf_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.osirrc.ciff.Posting)
    }

    // @@protoc_insertion_point(class_scope:io.osirrc.ciff.Posting)
    private static final io.osirrc.ciff.CommonIndexFileFormat.Posting DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.osirrc.ciff.CommonIndexFileFormat.Posting();
    }

    public static io.osirrc.ciff.CommonIndexFileFormat.Posting getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Posting>
        PARSER = new com.google.protobuf.AbstractParser<Posting>() {
      @java.lang.Override
      public Posting parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Posting(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Posting> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Posting> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.osirrc.ciff.CommonIndexFileFormat.Posting getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PostingsListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.osirrc.ciff.PostingsList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string term = 1;</code>
     */
    java.lang.String getTerm();
    /**
     * <code>string term = 1;</code>
     */
    com.google.protobuf.ByteString
        getTermBytes();

    /**
     * <code>int64 df = 2;</code>
     */
    long getDf();

    /**
     * <code>int64 cf = 3;</code>
     */
    long getCf();

    /**
     * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
     */
    java.util.List<io.osirrc.ciff.CommonIndexFileFormat.Posting> 
        getPostingsList();
    /**
     * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
     */
    io.osirrc.ciff.CommonIndexFileFormat.Posting getPostings(int index);
    /**
     * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
     */
    int getPostingsCount();
    /**
     * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
     */
    java.util.List<? extends io.osirrc.ciff.CommonIndexFileFormat.PostingOrBuilder> 
        getPostingsOrBuilderList();
    /**
     * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
     */
    io.osirrc.ciff.CommonIndexFileFormat.PostingOrBuilder getPostingsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code io.osirrc.ciff.PostingsList}
   */
  public  static final class PostingsList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.osirrc.ciff.PostingsList)
      PostingsListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostingsList.newBuilder() to construct.
    private PostingsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostingsList() {
      term_ = "";
      postings_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PostingsList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostingsList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              term_ = s;
              break;
            }
            case 16: {

              df_ = input.readInt64();
              break;
            }
            case 24: {

              cf_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                postings_ = new java.util.ArrayList<io.osirrc.ciff.CommonIndexFileFormat.Posting>();
                mutable_bitField0_ |= 0x00000001;
              }
              postings_.add(
                  input.readMessage(io.osirrc.ciff.CommonIndexFileFormat.Posting.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          postings_ = java.util.Collections.unmodifiableList(postings_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_PostingsList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_PostingsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.osirrc.ciff.CommonIndexFileFormat.PostingsList.class, io.osirrc.ciff.CommonIndexFileFormat.PostingsList.Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private volatile java.lang.Object term_;
    /**
     * <code>string term = 1;</code>
     */
    public java.lang.String getTerm() {
      java.lang.Object ref = term_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        term_ = s;
        return s;
      }
    }
    /**
     * <code>string term = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTermBytes() {
      java.lang.Object ref = term_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        term_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DF_FIELD_NUMBER = 2;
    private long df_;
    /**
     * <code>int64 df = 2;</code>
     */
    public long getDf() {
      return df_;
    }

    public static final int CF_FIELD_NUMBER = 3;
    private long cf_;
    /**
     * <code>int64 cf = 3;</code>
     */
    public long getCf() {
      return cf_;
    }

    public static final int POSTINGS_FIELD_NUMBER = 4;
    private java.util.List<io.osirrc.ciff.CommonIndexFileFormat.Posting> postings_;
    /**
     * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
     */
    public java.util.List<io.osirrc.ciff.CommonIndexFileFormat.Posting> getPostingsList() {
      return postings_;
    }
    /**
     * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
     */
    public java.util.List<? extends io.osirrc.ciff.CommonIndexFileFormat.PostingOrBuilder> 
        getPostingsOrBuilderList() {
      return postings_;
    }
    /**
     * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
     */
    public int getPostingsCount() {
      return postings_.size();
    }
    /**
     * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
     */
    public io.osirrc.ciff.CommonIndexFileFormat.Posting getPostings(int index) {
      return postings_.get(index);
    }
    /**
     * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
     */
    public io.osirrc.ciff.CommonIndexFileFormat.PostingOrBuilder getPostingsOrBuilder(
        int index) {
      return postings_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTermBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, term_);
      }
      if (df_ != 0L) {
        output.writeInt64(2, df_);
      }
      if (cf_ != 0L) {
        output.writeInt64(3, cf_);
      }
      for (int i = 0; i < postings_.size(); i++) {
        output.writeMessage(4, postings_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTermBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, term_);
      }
      if (df_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, df_);
      }
      if (cf_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, cf_);
      }
      for (int i = 0; i < postings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, postings_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.osirrc.ciff.CommonIndexFileFormat.PostingsList)) {
        return super.equals(obj);
      }
      io.osirrc.ciff.CommonIndexFileFormat.PostingsList other = (io.osirrc.ciff.CommonIndexFileFormat.PostingsList) obj;

      if (!getTerm()
          .equals(other.getTerm())) return false;
      if (getDf()
          != other.getDf()) return false;
      if (getCf()
          != other.getCf()) return false;
      if (!getPostingsList()
          .equals(other.getPostingsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + getTerm().hashCode();
      hash = (37 * hash) + DF_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDf());
      hash = (37 * hash) + CF_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCf());
      if (getPostingsCount() > 0) {
        hash = (37 * hash) + POSTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getPostingsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.osirrc.ciff.CommonIndexFileFormat.PostingsList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.osirrc.ciff.PostingsList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.osirrc.ciff.PostingsList)
        io.osirrc.ciff.CommonIndexFileFormat.PostingsListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_PostingsList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_PostingsList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.osirrc.ciff.CommonIndexFileFormat.PostingsList.class, io.osirrc.ciff.CommonIndexFileFormat.PostingsList.Builder.class);
      }

      // Construct using io.osirrc.ciff.CommonIndexFileFormat.PostingsList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPostingsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        term_ = "";

        df_ = 0L;

        cf_ = 0L;

        if (postingsBuilder_ == null) {
          postings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          postingsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_PostingsList_descriptor;
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.PostingsList getDefaultInstanceForType() {
        return io.osirrc.ciff.CommonIndexFileFormat.PostingsList.getDefaultInstance();
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.PostingsList build() {
        io.osirrc.ciff.CommonIndexFileFormat.PostingsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.PostingsList buildPartial() {
        io.osirrc.ciff.CommonIndexFileFormat.PostingsList result = new io.osirrc.ciff.CommonIndexFileFormat.PostingsList(this);
        int from_bitField0_ = bitField0_;
        result.term_ = term_;
        result.df_ = df_;
        result.cf_ = cf_;
        if (postingsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            postings_ = java.util.Collections.unmodifiableList(postings_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.postings_ = postings_;
        } else {
          result.postings_ = postingsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.osirrc.ciff.CommonIndexFileFormat.PostingsList) {
          return mergeFrom((io.osirrc.ciff.CommonIndexFileFormat.PostingsList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.osirrc.ciff.CommonIndexFileFormat.PostingsList other) {
        if (other == io.osirrc.ciff.CommonIndexFileFormat.PostingsList.getDefaultInstance()) return this;
        if (!other.getTerm().isEmpty()) {
          term_ = other.term_;
          onChanged();
        }
        if (other.getDf() != 0L) {
          setDf(other.getDf());
        }
        if (other.getCf() != 0L) {
          setCf(other.getCf());
        }
        if (postingsBuilder_ == null) {
          if (!other.postings_.isEmpty()) {
            if (postings_.isEmpty()) {
              postings_ = other.postings_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePostingsIsMutable();
              postings_.addAll(other.postings_);
            }
            onChanged();
          }
        } else {
          if (!other.postings_.isEmpty()) {
            if (postingsBuilder_.isEmpty()) {
              postingsBuilder_.dispose();
              postingsBuilder_ = null;
              postings_ = other.postings_;
              bitField0_ = (bitField0_ & ~0x00000001);
              postingsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPostingsFieldBuilder() : null;
            } else {
              postingsBuilder_.addAllMessages(other.postings_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.osirrc.ciff.CommonIndexFileFormat.PostingsList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.osirrc.ciff.CommonIndexFileFormat.PostingsList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object term_ = "";
      /**
       * <code>string term = 1;</code>
       */
      public java.lang.String getTerm() {
        java.lang.Object ref = term_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          term_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string term = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTermBytes() {
        java.lang.Object ref = term_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          term_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string term = 1;</code>
       */
      public Builder setTerm(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string term = 1;</code>
       */
      public Builder clearTerm() {
        
        term_ = getDefaultInstance().getTerm();
        onChanged();
        return this;
      }
      /**
       * <code>string term = 1;</code>
       */
      public Builder setTermBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        term_ = value;
        onChanged();
        return this;
      }

      private long df_ ;
      /**
       * <code>int64 df = 2;</code>
       */
      public long getDf() {
        return df_;
      }
      /**
       * <code>int64 df = 2;</code>
       */
      public Builder setDf(long value) {
        
        df_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 df = 2;</code>
       */
      public Builder clearDf() {
        
        df_ = 0L;
        onChanged();
        return this;
      }

      private long cf_ ;
      /**
       * <code>int64 cf = 3;</code>
       */
      public long getCf() {
        return cf_;
      }
      /**
       * <code>int64 cf = 3;</code>
       */
      public Builder setCf(long value) {
        
        cf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 cf = 3;</code>
       */
      public Builder clearCf() {
        
        cf_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<io.osirrc.ciff.CommonIndexFileFormat.Posting> postings_ =
        java.util.Collections.emptyList();
      private void ensurePostingsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          postings_ = new java.util.ArrayList<io.osirrc.ciff.CommonIndexFileFormat.Posting>(postings_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.osirrc.ciff.CommonIndexFileFormat.Posting, io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder, io.osirrc.ciff.CommonIndexFileFormat.PostingOrBuilder> postingsBuilder_;

      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public java.util.List<io.osirrc.ciff.CommonIndexFileFormat.Posting> getPostingsList() {
        if (postingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(postings_);
        } else {
          return postingsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public int getPostingsCount() {
        if (postingsBuilder_ == null) {
          return postings_.size();
        } else {
          return postingsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public io.osirrc.ciff.CommonIndexFileFormat.Posting getPostings(int index) {
        if (postingsBuilder_ == null) {
          return postings_.get(index);
        } else {
          return postingsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public Builder setPostings(
          int index, io.osirrc.ciff.CommonIndexFileFormat.Posting value) {
        if (postingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostingsIsMutable();
          postings_.set(index, value);
          onChanged();
        } else {
          postingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public Builder setPostings(
          int index, io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder builderForValue) {
        if (postingsBuilder_ == null) {
          ensurePostingsIsMutable();
          postings_.set(index, builderForValue.build());
          onChanged();
        } else {
          postingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public Builder addPostings(io.osirrc.ciff.CommonIndexFileFormat.Posting value) {
        if (postingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostingsIsMutable();
          postings_.add(value);
          onChanged();
        } else {
          postingsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public Builder addPostings(
          int index, io.osirrc.ciff.CommonIndexFileFormat.Posting value) {
        if (postingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostingsIsMutable();
          postings_.add(index, value);
          onChanged();
        } else {
          postingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public Builder addPostings(
          io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder builderForValue) {
        if (postingsBuilder_ == null) {
          ensurePostingsIsMutable();
          postings_.add(builderForValue.build());
          onChanged();
        } else {
          postingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public Builder addPostings(
          int index, io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder builderForValue) {
        if (postingsBuilder_ == null) {
          ensurePostingsIsMutable();
          postings_.add(index, builderForValue.build());
          onChanged();
        } else {
          postingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public Builder addAllPostings(
          java.lang.Iterable<? extends io.osirrc.ciff.CommonIndexFileFormat.Posting> values) {
        if (postingsBuilder_ == null) {
          ensurePostingsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, postings_);
          onChanged();
        } else {
          postingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public Builder clearPostings() {
        if (postingsBuilder_ == null) {
          postings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          postingsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public Builder removePostings(int index) {
        if (postingsBuilder_ == null) {
          ensurePostingsIsMutable();
          postings_.remove(index);
          onChanged();
        } else {
          postingsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder getPostingsBuilder(
          int index) {
        return getPostingsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public io.osirrc.ciff.CommonIndexFileFormat.PostingOrBuilder getPostingsOrBuilder(
          int index) {
        if (postingsBuilder_ == null) {
          return postings_.get(index);  } else {
          return postingsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public java.util.List<? extends io.osirrc.ciff.CommonIndexFileFormat.PostingOrBuilder> 
           getPostingsOrBuilderList() {
        if (postingsBuilder_ != null) {
          return postingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(postings_);
        }
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder addPostingsBuilder() {
        return getPostingsFieldBuilder().addBuilder(
            io.osirrc.ciff.CommonIndexFileFormat.Posting.getDefaultInstance());
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder addPostingsBuilder(
          int index) {
        return getPostingsFieldBuilder().addBuilder(
            index, io.osirrc.ciff.CommonIndexFileFormat.Posting.getDefaultInstance());
      }
      /**
       * <code>repeated .io.osirrc.ciff.Posting postings = 4;</code>
       */
      public java.util.List<io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder> 
           getPostingsBuilderList() {
        return getPostingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.osirrc.ciff.CommonIndexFileFormat.Posting, io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder, io.osirrc.ciff.CommonIndexFileFormat.PostingOrBuilder> 
          getPostingsFieldBuilder() {
        if (postingsBuilder_ == null) {
          postingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.osirrc.ciff.CommonIndexFileFormat.Posting, io.osirrc.ciff.CommonIndexFileFormat.Posting.Builder, io.osirrc.ciff.CommonIndexFileFormat.PostingOrBuilder>(
                  postings_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          postings_ = null;
        }
        return postingsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.osirrc.ciff.PostingsList)
    }

    // @@protoc_insertion_point(class_scope:io.osirrc.ciff.PostingsList)
    private static final io.osirrc.ciff.CommonIndexFileFormat.PostingsList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.osirrc.ciff.CommonIndexFileFormat.PostingsList();
    }

    public static io.osirrc.ciff.CommonIndexFileFormat.PostingsList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostingsList>
        PARSER = new com.google.protobuf.AbstractParser<PostingsList>() {
      @java.lang.Override
      public PostingsList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PostingsList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostingsList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostingsList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.osirrc.ciff.CommonIndexFileFormat.PostingsList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DocRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.osirrc.ciff.DocRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 docid = 1;</code>
     */
    int getDocid();

    /**
     * <code>string collection_docid = 2;</code>
     */
    java.lang.String getCollectionDocid();
    /**
     * <code>string collection_docid = 2;</code>
     */
    com.google.protobuf.ByteString
        getCollectionDocidBytes();

    /**
     * <code>int32 doclength = 3;</code>
     */
    int getDoclength();
  }
  /**
   * Protobuf type {@code io.osirrc.ciff.DocRecord}
   */
  public  static final class DocRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.osirrc.ciff.DocRecord)
      DocRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DocRecord.newBuilder() to construct.
    private DocRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DocRecord() {
      collectionDocid_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DocRecord();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DocRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              docid_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              collectionDocid_ = s;
              break;
            }
            case 24: {

              doclength_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_DocRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_DocRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.osirrc.ciff.CommonIndexFileFormat.DocRecord.class, io.osirrc.ciff.CommonIndexFileFormat.DocRecord.Builder.class);
    }

    public static final int DOCID_FIELD_NUMBER = 1;
    private int docid_;
    /**
     * <code>int32 docid = 1;</code>
     */
    public int getDocid() {
      return docid_;
    }

    public static final int COLLECTION_DOCID_FIELD_NUMBER = 2;
    private volatile java.lang.Object collectionDocid_;
    /**
     * <code>string collection_docid = 2;</code>
     */
    public java.lang.String getCollectionDocid() {
      java.lang.Object ref = collectionDocid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        collectionDocid_ = s;
        return s;
      }
    }
    /**
     * <code>string collection_docid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCollectionDocidBytes() {
      java.lang.Object ref = collectionDocid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        collectionDocid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCLENGTH_FIELD_NUMBER = 3;
    private int doclength_;
    /**
     * <code>int32 doclength = 3;</code>
     */
    public int getDoclength() {
      return doclength_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (docid_ != 0) {
        output.writeInt32(1, docid_);
      }
      if (!getCollectionDocidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, collectionDocid_);
      }
      if (doclength_ != 0) {
        output.writeInt32(3, doclength_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (docid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, docid_);
      }
      if (!getCollectionDocidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, collectionDocid_);
      }
      if (doclength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, doclength_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.osirrc.ciff.CommonIndexFileFormat.DocRecord)) {
        return super.equals(obj);
      }
      io.osirrc.ciff.CommonIndexFileFormat.DocRecord other = (io.osirrc.ciff.CommonIndexFileFormat.DocRecord) obj;

      if (getDocid()
          != other.getDocid()) return false;
      if (!getCollectionDocid()
          .equals(other.getCollectionDocid())) return false;
      if (getDoclength()
          != other.getDoclength()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOCID_FIELD_NUMBER;
      hash = (53 * hash) + getDocid();
      hash = (37 * hash) + COLLECTION_DOCID_FIELD_NUMBER;
      hash = (53 * hash) + getCollectionDocid().hashCode();
      hash = (37 * hash) + DOCLENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getDoclength();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.osirrc.ciff.CommonIndexFileFormat.DocRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.osirrc.ciff.DocRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.osirrc.ciff.DocRecord)
        io.osirrc.ciff.CommonIndexFileFormat.DocRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_DocRecord_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_DocRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.osirrc.ciff.CommonIndexFileFormat.DocRecord.class, io.osirrc.ciff.CommonIndexFileFormat.DocRecord.Builder.class);
      }

      // Construct using io.osirrc.ciff.CommonIndexFileFormat.DocRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        docid_ = 0;

        collectionDocid_ = "";

        doclength_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.osirrc.ciff.CommonIndexFileFormat.internal_static_io_osirrc_ciff_DocRecord_descriptor;
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.DocRecord getDefaultInstanceForType() {
        return io.osirrc.ciff.CommonIndexFileFormat.DocRecord.getDefaultInstance();
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.DocRecord build() {
        io.osirrc.ciff.CommonIndexFileFormat.DocRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.osirrc.ciff.CommonIndexFileFormat.DocRecord buildPartial() {
        io.osirrc.ciff.CommonIndexFileFormat.DocRecord result = new io.osirrc.ciff.CommonIndexFileFormat.DocRecord(this);
        result.docid_ = docid_;
        result.collectionDocid_ = collectionDocid_;
        result.doclength_ = doclength_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.osirrc.ciff.CommonIndexFileFormat.DocRecord) {
          return mergeFrom((io.osirrc.ciff.CommonIndexFileFormat.DocRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.osirrc.ciff.CommonIndexFileFormat.DocRecord other) {
        if (other == io.osirrc.ciff.CommonIndexFileFormat.DocRecord.getDefaultInstance()) return this;
        if (other.getDocid() != 0) {
          setDocid(other.getDocid());
        }
        if (!other.getCollectionDocid().isEmpty()) {
          collectionDocid_ = other.collectionDocid_;
          onChanged();
        }
        if (other.getDoclength() != 0) {
          setDoclength(other.getDoclength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.osirrc.ciff.CommonIndexFileFormat.DocRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.osirrc.ciff.CommonIndexFileFormat.DocRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int docid_ ;
      /**
       * <code>int32 docid = 1;</code>
       */
      public int getDocid() {
        return docid_;
      }
      /**
       * <code>int32 docid = 1;</code>
       */
      public Builder setDocid(int value) {
        
        docid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 docid = 1;</code>
       */
      public Builder clearDocid() {
        
        docid_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object collectionDocid_ = "";
      /**
       * <code>string collection_docid = 2;</code>
       */
      public java.lang.String getCollectionDocid() {
        java.lang.Object ref = collectionDocid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          collectionDocid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string collection_docid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCollectionDocidBytes() {
        java.lang.Object ref = collectionDocid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          collectionDocid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string collection_docid = 2;</code>
       */
      public Builder setCollectionDocid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        collectionDocid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string collection_docid = 2;</code>
       */
      public Builder clearCollectionDocid() {
        
        collectionDocid_ = getDefaultInstance().getCollectionDocid();
        onChanged();
        return this;
      }
      /**
       * <code>string collection_docid = 2;</code>
       */
      public Builder setCollectionDocidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        collectionDocid_ = value;
        onChanged();
        return this;
      }

      private int doclength_ ;
      /**
       * <code>int32 doclength = 3;</code>
       */
      public int getDoclength() {
        return doclength_;
      }
      /**
       * <code>int32 doclength = 3;</code>
       */
      public Builder setDoclength(int value) {
        
        doclength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 doclength = 3;</code>
       */
      public Builder clearDoclength() {
        
        doclength_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.osirrc.ciff.DocRecord)
    }

    // @@protoc_insertion_point(class_scope:io.osirrc.ciff.DocRecord)
    private static final io.osirrc.ciff.CommonIndexFileFormat.DocRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.osirrc.ciff.CommonIndexFileFormat.DocRecord();
    }

    public static io.osirrc.ciff.CommonIndexFileFormat.DocRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DocRecord>
        PARSER = new com.google.protobuf.AbstractParser<DocRecord>() {
      @java.lang.Override
      public DocRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DocRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DocRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DocRecord> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.osirrc.ciff.CommonIndexFileFormat.DocRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_osirrc_ciff_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_osirrc_ciff_Header_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_osirrc_ciff_Posting_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_osirrc_ciff_Posting_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_osirrc_ciff_PostingsList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_osirrc_ciff_PostingsList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_osirrc_ciff_DocRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_osirrc_ciff_DocRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-src/main/protobuf/CommonIndexFileForma" +
      "t.proto\022\016io.osirrc.ciff\"6\n\006Header\022\032\n\022num" +
      "_postings_lists\030\001 \001(\005\022\020\n\010num_docs\030\002 \001(\005\"" +
      "$\n\007Posting\022\r\n\005docid\030\001 \001(\005\022\n\n\002tf\030\002 \001(\005\"_\n" +
      "\014PostingsList\022\014\n\004term\030\001 \001(\t\022\n\n\002df\030\002 \001(\003\022" +
      "\n\n\002cf\030\003 \001(\003\022)\n\010postings\030\004 \003(\0132\027.io.osirr" +
      "c.ciff.Posting\"G\n\tDocRecord\022\r\n\005docid\030\001 \001" +
      "(\005\022\030\n\020collection_docid\030\002 \001(\t\022\021\n\tdoclengt" +
      "h\030\003 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_osirrc_ciff_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_osirrc_ciff_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_osirrc_ciff_Header_descriptor,
        new java.lang.String[] { "NumPostingsLists", "NumDocs", });
    internal_static_io_osirrc_ciff_Posting_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_osirrc_ciff_Posting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_osirrc_ciff_Posting_descriptor,
        new java.lang.String[] { "Docid", "Tf", });
    internal_static_io_osirrc_ciff_PostingsList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_osirrc_ciff_PostingsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_osirrc_ciff_PostingsList_descriptor,
        new java.lang.String[] { "Term", "Df", "Cf", "Postings", });
    internal_static_io_osirrc_ciff_DocRecord_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_osirrc_ciff_DocRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_osirrc_ciff_DocRecord_descriptor,
        new java.lang.String[] { "Docid", "CollectionDocid", "Doclength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
